/**
 * Random project name generator
 * Combines adjectives and nouns to create unique, memorable project names
 */

const ADJECTIVES: readonly string[] = [
  // Original 50
  "Amber",
  "Azure",
  "Bold",
  "Brave",
  "Bright",
  "Calm",
  "Clever",
  "Coral",
  "Cosmic",
  "Crisp",
  "Crystal",
  "Dapper",
  "Daring",
  "Dreamy",
  "Electric",
  "Elegant",
  "Emerald",
  "Fancy",
  "Fierce",
  "Fluffy",
  "Fuzzy",
  "Gentle",
  "Gilded",
  "Golden",
  "Happy",
  "Hidden",
  "Icy",
  "Jade",
  "Jolly",
  "Keen",
  "Lucky",
  "Lunar",
  "Marble",
  "Misty",
  "Neon",
  "Noble",
  "Plucky",
  "Polar",
  "Quiet",
  "Radiant",
  "Rustic",
  "Secret",
  "Silver",
  "Sleek",
  "Solar",
  "Swift",
  "Velvet",
  "Wild",
  "Witty",
  "Zesty",
  // Added 50
  "Ancient",
  "Atomic",
  "Bouncy",
  "Breezy",
  "Bubbly",
  "Charming",
  "Cheerful",
  "Cozy",
  "Crimson",
  "Curious",
  "Dancing",
  "Dazzling",
  "Distant",
  "Dusty",
  "Enchanted",
  "Frosty",
  "Gleaming",
  "Glowing",
  "Gusty",
  "Hazy",
  "Humble",
  "Infinite",
  "Jazzy",
  "Lively",
  "Luminous",
  "Magical",
  "Mellow",
  "Mighty",
  "Mystic",
  "Nimble",
  "Painted",
  "Peaceful",
  "Peppy",
  "Playful",
  "Puffy",
  "Rosy",
  "Sandy",
  "Shiny",
  "Silky",
  "Snowy",
  "Sparkling",
  "Spicy",
  "Starry",
  "Stormy",
  "Sunny",
  "Tangy",
  "Tender",
  "Twilight",
  "Vibrant",
  "Whimsy",
] as const;

const NOUNS: readonly string[] = [
  // Original 50
  "Anchor",
  "Arrow",
  "Badger",
  "Beacon",
  "Blossom",
  "Breeze",
  "Canyon",
  "Castle",
  "Cloud",
  "Compass",
  "Coral",
  "Crane",
  "Dawn",
  "Dolphin",
  "Dragon",
  "Falcon",
  "Feather",
  "Fern",
  "Finch",
  "Forge",
  "Fox",
  "Galaxy",
  "Glacier",
  "Grove",
  "Harbor",
  "Horizon",
  "Ivy",
  "Lantern",
  "Lighthouse",
  "Lotus",
  "Meadow",
  "Moon",
  "Mountain",
  "Oak",
  "Ocean",
  "Orchid",
  "Owl",
  "Pebble",
  "Phoenix",
  "Pine",
  "Prism",
  "Raven",
  "River",
  "Sequoia",
  "Sparrow",
  "Storm",
  "Sunset",
  "Tiger",
  "Valley",
  "Willow",
  // Added 50
  "Acorn",
  "Aurora",
  "Bear",
  "Birch",
  "Bluebird",
  "Brook",
  "Butterfly",
  "Cedar",
  "Cinder",
  "Clover",
  "Comet",
  "Cove",
  "Cricket",
  "Daisy",
  "Dewdrop",
  "Dragonfly",
  "Dune",
  "Echo",
  "Ember",
  "Firefly",
  "Fountain",
  "Geyser",
  "Heron",
  "Honeybee",
  "Iris",
  "Kite",
  "Lagoon",
  "Lark",
  "Lily",
  "Maple",
  "Marigold",
  "Meteor",
  "Moss",
  "Nebula",
  "Oasis",
  "Otter",
  "Panther",
  "Pelican",
  "Penguin",
  "Poppy",
  "Quill",
  "Rainbow",
  "Reef",
  "Robin",
  "Sage",
  "Seashell",
  "Snowflake",
  "Sunflower",
  "Thistle",
  "Whale",
] as const;

/**
 * Generates a random project name by combining an adjective and noun
 * @returns A string in the format "Adjective Noun" (e.g., "Fuzzy Fish")
 */
export function generateProjectName(): string {
  const adjective = ADJECTIVES[Math.floor(Math.random() * ADJECTIVES.length)];
  const noun = NOUNS[Math.floor(Math.random() * NOUNS.length)];
  return `${adjective} ${noun}`;
}

/**
 * Generates multiple unique project name suggestions
 * @param count - Number of unique names to generate (max limited by combinations)
 * @returns Array of unique project names
 */
export function generateProjectNameSuggestions(count: number): string[] {
  const maxCombinations = ADJECTIVES.length * NOUNS.length;
  const safeCount = Math.min(count, maxCombinations);
  const names = new Set<string>();

  while (names.size < safeCount) {
    names.add(generateProjectName());
  }

  return Array.from(names);
}
